CREATE TABLE UP_USER (
    USER_ID BINARY(16) NOT NULL,
    FIRST_NAME VARCHAR(255 ) NOT NULL,
    LAST_NAME VARCHAR(255 ) NOT NULL,
    FISCAL_CODE VARCHAR(255 ) NOT NULL UNIQUE,
    EMAIL VARCHAR(255 ) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(255 ) NOT NULL,
    TS_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TS_DELETE TIMESTAMP NULL,
    TS_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT up_user_pk PRIMARY KEY (USER_ID)
);

CREATE TABLE UP_USER_AUTHENTICATION (
    AUTH_ID NUMERIC NOT NULL,
    USER_ID BINARY(16) NOT NULL,
    USER_NAME VARCHAR(255 ) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255 ) NOT NULL,
    ACTIVE BOOLEAN  NOT NULL DEFAULT FALSE,
    ROLES VARCHAR(255 ) NOT NULL, -- sostituito con tabella apposita ruoli e privilegi
    TS_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TS_DELETE TIMESTAMP NULL,
    TS_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT up_user_authentication_pk PRIMARY KEY (AUTH_ID),
    CONSTRAINT up_user_authentication_fk FOREIGN KEY (USER_ID) REFERENCES up_user(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE UP_PERMISSION (
    USER_ID  BINARY(16) NOT NULL,
    PERMISSION_ID BINARY(16) NOT NULL,
    TS_START DATETIME DEFAULT CURRENT_TIMESTAMP,
    TS_END DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION VARCHAR(255 ),
    --TYPE SMALLINT NOT NULL,
    PERMISSION_TYPE_ID NUMERIC NOT NULL,
    VALIDATED BOOLEAN  NOT NULL DEFAULT FALSE,
    TS_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TS_DELETE TIMESTAMP NULL,
    TS_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT up_permission_pk PRIMARY KEY (USER_ID, PERMISSION_ID),
    CONSTRAINT up_permission_fk FOREIGN KEY (USER_ID) REFERENCES up_user(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT up_permission_type_fk FOREIGN KEY (PERMISSION_TYPE_ID) REFERENCES UP_PERMISSION_TYPE(PERMISSION_TYPE_ID)
);

CREATE TABLE UP_PERMISSION_TYPE (
    PERMISSION_TYPE_ID NUMERIC NOT NULL,
    NAME VARCHAR(128 ) UNIQUE,
    DESCRIPTION VARCHAR(255 ),
    ACTIVE BOOLEAN  NOT NULL DEFAULT FALSE,
    TS_CREATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TS_DELETE TIMESTAMP NULL,
    TS_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT up_permission_type_pk PRIMARY KEY (PERMISSION_TYPE_ID)
)